### ISSUE TITLE
[doc] Requisitos

### ISSUE THREAD

**Issue by guilhermednt** [guilhermednt/login-cidadao#12]
Requisitos que devem ser atendidos para a execução do Login Cidadão

**Comment by guilhermednt** [comment]
Item atendido no arquivo:
https://github.com/guilhermednt/login-cidadao/blob/docs/doc/docs.md

**Comment by vitor-kato** [comment]
https://github.com/guilhermednt/login-cidadao/blob/docs/doc/deploy.md
