### ISSUE TITLE
[doc] Gerenciamento de Roles via cli

### ISSUE THREAD

**Issue by guilhermednt** [guilhermednt/login-cidadao#14]
Demonstrar como se faz o gerenciamento de Roles a partir da linha de comandos.

**Comment by guilhermednt** [comment]
Verificar se o que foi feito no `user_management.md` atende ou precisa ser expandido.

**Comment by thaisrigolon** [comment]
@vitor-kato, por favor, checar essa issue.

**Comment by intrepidocabral** [comment]
acho que isso aqui resolve o problema: https://github.com/guilhermednt/login-cidadao/blob/docs/doc/config_user_management.md

Fiz a junção do que estava no cookbook com o user_management.
