### ISSUE TITLE
[doc] Breve introdução a CLI do Symfony

### ISSUE THREAD

**Issue by guilhermednt** [guilhermednt/login-cidadao#25]
Ressaltar que:

 - [x] Deve-se logar como o usuário que executa o Login Cidadão;
 - [x] Deve-se executar os comandos na raiz do projeto.

Ver [este comentário](https://github.com/guilhermednt/login-cidadao/issues/24#issuecomment-288149004).

**Comment by guilhermednt** [comment]
@vitor-kato conforme comentado [aqui na issue #24](https://github.com/guilhermednt/login-cidadao/issues/24#issuecomment-288172148).

**Comment by vitor-kato** [comment]
@guilhermednt Acho que com essa parte da documentação fica mas clara o que deve ser feito em relação aos comandos do Symfony, mas acho válido referenciar esse documento nesse outro

https://github.com/guilhermednt/login-cidadao/blob/docs/doc/cookbook/admin_user.md

Para quem tiver maiores problemas

**Comment by guilhermednt** [comment]
Feito, @vitor-kato :+1:

**Comment by vitor-kato** [comment]
Ok para essa issue!

**Comment by intrepidocabral** [comment]
ok! Achei que ficou bem interessante. Poderia ter uma sessão de "outros exemplos", mas no geral está ok! estou fechando essa issue pq acho que ela contempla a necessidade.
