### ISSUE TITLE
[doc] Deploy

### ISSUE THREAD

**Issue by thaisrigolon** [guilhermednt/login-cidadao#3]
2.1 Manual de deploy passo-a-passo como receita.
Criar uma documentação detalhada de deploy orientada ao sysadmin. A documentação atual, se executada como "receita de bolo" ela não produz uma instalação ativa. Essa documentação tem que ser revista e rescrita, com vistas a facilitar o trabalho do sysadmin. Como se trata de um software de autenticação, alguns conceitos podem não estar bem definidos ou serem de conhecimento fácil de um sysadmin. Um boa documentação deveria contemplar a explicação desses termos.

**Comment by guilhermednt** [comment]
Item atendido no arquivo:
https://github.com/guilhermednt/login-cidadao/blob/docs/doc/docs.md

**Comment by intrepidocabral** [comment]
- Não há comandos para a criação ou configuração da base de dados em nenhum momento durante a documentação. Sem esses comandos há erros onde é impossível continuar a instalação correta. Essa issue deve ser uma receita de bolo completa, o usuário deve executá-la sem ter que se ater a muitos conhecimentos extras para completá-la com sucesso. 

Recomendação: 

- Documentação deve sugerir o uso de um sgbd em específico. Postgres por exemplo;
- Deve demonstrar como instalar o pacote do sgbd sugerido, criar o user e criar a base; 

Exemplo da documentação atual que funciona como receita: 

 ```bash
    // Atualize a lista de pacotes do seu servidor
    $ sudo apt-get update

    // Instale o servidor Nginx 
    $ sudo apt-get install nginx
    //obs: se o apache estiver instalado ele pode dar conflito com o Nginx. 
    // Fique atento para a necessidade de desinstalá-lo. 

    //Caso tenha algum gerenciador de bases de dados(mysql ou postgres) você poderá usá-lo. 
    //Se não tiver, instale o banco que quer usar. Optamos aqui por postgres
    $ sudo apt-get install postgresql postgresql-client

    // Instale o git para auxiliá-lo no processo de obtenção do código da aplicação
    $ sudo apt-get install git

    // Instalando pacote do server memcached 
    $ sudo apt-get install memcached
    
    // Instalando pacotes do php. 
    // Observe que aqui vamos optar por usar o postgres, mas é possível usar mysql sem problemas
    $ sudo apt-get install php5 php5-cli php5-fpm php5-curl php5-intl php5-pgsql php5-memcache
       
    // Instalando nodejs
    $ sudo curl -sL https://deb.nodesource.com/setup_4.x | bash -
    $ sudo apt-get install --yes nodejs

```

Exemplo da documentação atual que funciona: 

> Crie um usuário no postgres e depois uma base. Sugerimos usar o mesmo nome. 

```
  //Como root, crie um usuário que funcionará via socket
  # sudo -u postgres psql -c "CREATE USER logincidadao"
  // Em seguinda, crie a base de dados
  # sudo -u postgres createdb --owner logincidadao logincidadao

```

**Comment by vitor-kato** [comment]
- Informações muito dispersas entre várias documentações diferentes e não claras o suficiente, como a configuração do arquivo de “parameters.yml”. Onde não se fala como se deve configurar como por exemplo para uma instalação de testes.

Recomendação: 
- Mais detalhes sobre a configuração dos parameters
- Exemplo de como seria configurado por exemplo em um servidor de teste

**Comment by vitor-kato** [comment]
- Recomenda-se o uso de Let’s Encrypt, mas na instalação faz procedimentos de OpenSSL. E não apresenta em nenhum lugar como seria feito com Let’s Encrypt. 

Recomendação:
- Usar apenas um dos certificados
- Exemplo passo a passo de como criar o certificado

**Comment by guilhermednt** [comment]
Em relação ao [comentário](https://github.com/guilhermednt/login-cidadao/issues/3#issuecomment-279468104) do @robertkapa:

> Não há comandos para a criação ou configuração da base de dados em nenhum momento durante a documentação.

Há comandos para criação do banco de dados:

![selection_074](https://cloud.githubusercontent.com/assets/860796/23464103/867ccfc4-fe72-11e6-97c6-ba8ec9a1375f.png)

> Recomendação:
>
> Documentação deve sugerir o uso de um sgbd em específico. Postgres por exemplo;

As pessoas tem facilidade com softwares diferentes, portanto optei por recomendar os dois suportados pelo Login Cidadão. Há alguma razão em específico para recomendar um software sendo que ambos atenderão plenamente?

> Deve demonstrar como instalar o pacote do sgbd sugerido, criar o user e criar a base;

Isso varia entre MySQL e Postgres, além do processo de instalação variar muito entre cada distro. Não acredito que deva estar no escopo do Login Cidadão ensinar o SysAdmin a instalar banco de dados quando a própria documentação desses softwares já faz isso de forma competente.

A documentação atual só funciona em um sistema operacional e com um SGBD. Vejo a nova documentação como uma evolução que permite instalar o Login Cidadão em qualquer sistema operacional.

**Comment by guilhermednt** [comment]
Em relação ao [primeiro comentário](https://github.com/guilhermednt/login-cidadao/issues/3#issuecomment-279480434) do @vitor-kato:

> Informações muito dispersas entre várias documentações diferentes e não claras o suficiente,

Essas duas características me parecem mutuamente excludentes. Quanto mais longo um texto, mais confuso ele tende a ser e, portanto, menos claro. Poderia dar um exemplo específico do que não ficou claro?

> como a configuração do arquivo de “parameters.yml”. Onde não se fala como se deve configurar como por exemplo para uma instalação de testes.

Não se fala como deve ser configurada uma instância de testes pois não há diferença entre o ambiente de produção, desenvolvimento e testes em relação ao `parameters.yml`. Em nenhum momento é insinuado que há essa diferença, caso tenha entendido dessa forma, por favor aponte o trecho que lhe fez entender assim que eu tento deixar mais claro.

> Mais detalhes sobre a configuração dos parameters

Já há [um arquivo inteiro](https://github.com/guilhermednt/login-cidadao/blob/docs/doc/parameters.md) dedicado a descrever cada um dos parâmetros disponíveis no Login Cidadão. Acredito que podemos melhorar as descrições, mas isso certamente vai ficar bastante complexo.

--------

Em relação ao [segundo comentário](https://github.com/guilhermednt/login-cidadao/issues/3#issuecomment-279481634) do @vitor-kato:

> Recomenda-se o uso de Let’s Encrypt, mas na instalação faz procedimentos de OpenSSL. E não apresenta em nenhum lugar como seria feito com Let’s Encrypt.

Corrigi adicionando orientações de como proceder para utilizar Let's Encrypt. Entretanto não entendi o que o procedimento com openssl (criação do `dhparam.pem`) tem a ver com a falta de instruções do Let's Entrypt, poderia elaborar mais?

**Comment by vitor-kato** [comment]
Issue contemplada em outras issues
