### ISSUE TITLE
[doc] API

### ISSUE THREAD

**Issue by thaisrigolon** [guilhermednt/login-cidadao#5]
- [x] 4.1 Tipo de api usada, tipo de chamadas possíveis, etc
- [x] 4.2 Tenho uma aplicação e quero usar OAuth2 ou OpenID, como posso integrar com login?

**Comment by vitor-kato** [comment]
Ok para essa parte também, acho que já está bem informativa do jeito que está. Podendo ser melhorada junto com o desenvolvimento do LC
