### ISSUE TITLE
[doc] Manutenção

### ISSUE THREAD

**Issue by thaisrigolon** [guilhermednt/login-cidadao#6]
5.1 Documentação de manutenção do sistema: gerenciar usuários, mudar eventuais configurações, senhas, etc

- [x] Manutenção
- [x] Gerenciar usuários
- [x] Configurações

Gerenciamento de Roles via cli: #14

**Comment by vitor-kato** [comment]
@thaisrigolon **Gerenciar usuários** em:

https://github.com/guilhermednt/login-cidadao/blob/docs/doc/user_management.md

**Comment by vitor-kato** [comment]
@guilhermednt  Na parte de `A permissão que controla esse tipo de acesso é ROLE_VIEW_USERS_CPF.` 

Acho que vale a pena deixar mais claro o que é isso como fazer alguma alteração caso o usuário queira e onde encontrar.

**Comment by guilhermednt** [comment]
@vitor-kato que tal agora? Detalhei mais as funcionalidades de gerenciamento de usuários e expliquei algumas "filosofias" atreladas a essas atividades.

**Comment by vitor-kato** [comment]
Ok para essa issue!
