### ISSUE TITLE
[doc] Pontos obsoletos da documentação

### ISSUE THREAD

**Issue by thaisrigolon** [guilhermednt/login-cidadao#8]
Alguns pontos obsoletos da atual documentação devem ser revistos e retirados caso não tenham mais utilidade para a nova documentação.

**Comment by guilhermednt** [comment]
Como está tudo sendo reescrito, acho que esse issue está resolvido automaticamente.

**Comment by vitor-kato** [comment]
Só falta o merge

**Comment by vitor-kato** [comment]
Aguardando Review @photonauta35 

https://github.com/redelivre/login-cidadao/pull/177
