### ISSUE TITLE
Cobrir softwares correlatos para funcionamento da aplicação

### ISSUE THREAD

**Issue by thaisrigolon** [guilhermednt/login-cidadao#9]
A documentação deve cobrir os softwares correlatos para o funcionamento da aplicação: php-fpm, nginx, postgres. Ao menos o essencial de uso desses sistemas, pontos importantes que não devem ser deixados de lado. Nada muito complexo, mas algo que possa dar subsídio para o sysadmin

**Comment by guilhermednt** [comment]
Coberto no #3
